name: Train MLflow Model CI

on: 
  workflow_dispatch: 
  push: 
    paths: 
      - 'MLProject/**'

jobs: 
  train: 
    runs-on: ubuntu-latest    
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy

      - name: Run MLflow Script Directly
        run: |
          export MLFLOW_TRACKING_URI=./mlruns
          python MLProject/modelling.py

      - name: Debug — List files
        run: ls -R

      - name: Configure Git with PAT
        run: |
          git config --global user.name "Nemophiliaa"
          git config --global user.email "neemophilia@gmail.com"
          git remote set-url origin https://Nemophiliaa:${{ secrets.PAT }}@github.com/Nemophiliaa/HeartDiagnosa-CI-.git

      - name: Save mlruns to Repo
        run: |
          if [ -d "mlruns" ]; then
            git add mlruns/
            git commit -m "save mlruns from CI" || echo "No changes to commit"
            git push origin main
          else
            echo "Folder mlruns/ tidak ditemukan. Gagal menyimpan artefak."
          fi
